version: "3.9"

services:
  database: 
    image: postgres
    container_name: database_boticario
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=boticario
    volumes:
      - pgdata:/data/postgres

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=docker
      
  # app:
  #   build: .
  #   container_name: api_boticario
  #   restart: always
  #   ports: 
  #     - 3333:3333
  #     - 9229:9229
  #   volumes: 
  #     - .:/usr/app
  #   links: 
  #     - database
  #   depends_on:
  #     - database



volumes:
  pgdata:
    driver: local